### ISSUE TITLE
[FE-01] 메인페이지 퍼블리싱

### ISSUE THREAD

**Issue by hurryduck** [hurryduck/pixly#1]
# to-do
- [x] 중앙 상단에 메인 문구 노출
- [x] 상품 썸네일 예시 이미지 노출
- [x] 이미지 업로드 공간 노출
