### ISSUE TITLE
[FE-02] 메인페이지 사용자는 이미지 업로드할 수 있다.

### ISSUE THREAD

**Issue by hurryduck** [hurryduck/pixly#2]
# to-do
## 이미지 업로드 버튼
- [x] 이미지 업로드 버튼 클릭
- [x] 파일 업로드창 노출
- [x] 파일 선택시 서비스 페이지로 이동
## 이미지 업로드 드래그 앤 드롭
- [x] 이미지 드래그 앤 드롭시 서비스 페이지로 이동
