### ISSUE TITLE
[FE-03] 서비스페이지 퍼블리싱

### ISSUE THREAD

**Issue by hurryduck** [hurryduck/pixly#3]
# to-do
## 본문
- [x] 생성된 이미지 노출
- [x] 분위기별 생성된 이미지 노출
- [x] 저장하기 버튼 노출
- [x] 공유하기 버튼 노출
- [x] 추가 요청 사항 입력란 노출
- [x] 생성하기 버튼 노출
## 사이드바-인플루언서
- [x] 선택된 인플루언서 이미지 노출
- [x] 인플루언서 목록 노출
## 사이드바-상품이미지
- [x] 업로드된 상품 이미지 노출
- [x] 업로드된 상품 이미지 목록 노출
