### ISSUE TITLE
[FE-04] 서비스페이지 사용자는 이미지를 생성된 이미지를 확인할 수 있다.

### ISSUE THREAD

**Issue by hurryduck** [hurryduck/pixly#4]
# to-do
## 생성된 이미지 노출
- [x] 분위기별 생성된 이미지에서 첫 번째 기본 값 노출
## 분위별 생성된 이미지 노출
- [x] 네가지 분위기의 생성된 이미지 노출
- [x] 생성된 이미지 중 선택된 생성된 이미지는 아웃라인이 노출된다.
- [x] 다른 생성된 이미지 선택시 생성된 이미지 노출이 변경된다.
